kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: raptor
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32006 # otel-backend
        hostPort: 32006
        protocol: TCP
      - containerPort: 32010 # app
        hostPort: 32010
        protocol: TCP
