apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-backend
  template:
    metadata:
      labels:
        app: otel-backend
    spec:
      containers:
        - name: otel-backend
          image: ghcr.io/open-telemetry/opentelemetry-java-instrumentation/smoke-test-fake-backend:20221127.3559314891
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx128m"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 25
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 25
            periodSeconds: 15
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: otel-backend
  labels:
    app: otel-backend
spec:
  type: NodePort
  selector:
    app: otel-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32006
