name: Code quality checks

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**.md'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:
  k8s-e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - name: Clone the code
        uses: actions/checkout@v3
      - name: Cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install KiND
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build the injector container
        run: make -C integration-tests/k8s build-injector
        shell: bash

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Integration tests
        shell: bash
        run: |
          set -euo pipefail
          go test -v -timeout 1h -json -tags e2e integration-tests/k8s/... --args -v 5 -build-tag=$(git rev-parse --short HEAD) 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - name: Report failure
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 🐛 E2E failed for ${{ github.sha }}
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: bug
